#------------------------------------
# Github action part -1- basic
#copyleft DmN

name: my-basic

on:
  push:
    branches:
       -master
jobs:
  my_test:
   runs-on: ubuntu-latest
   
    steps:
    -name: print
    run: echo "basic"
  
  my_deploy:
   runs-on: ubuntu-latest
   
   steps:
    -name: print
    run: echo "end"
